### ISSUE TITLE
Err

### ISSUE THREAD

**Issue by tomzangsad** [Galaxy-VN/AuthMeUI#2]
![image](https://user-images.githubusercontent.com/63664294/184543867-9897a37c-a0b2-4155-b6b1-7727b1986349.png)

**Comment by Galaxy-VN** [comment]
Can you provide me what is you floodgate version?

**Comment by tomzangsad** [comment]
I am using the latest version

**Comment by tomzangsad** [comment]
master #73

**Comment by Galaxy-VN** [comment]
[AuthMeUI-1.0.2.zip](https://github.com/Galaxy-VN/AuthMeUI/files/9333642/AuthMeUI-1.0.2.zip)
Here i add a debug try a screenshot for me please

**Comment by tomzangsad** [comment]
still the same

**Comment by tomzangsad** [comment]
![image](https://user-images.githubusercontent.com/63664294/184567273-f755583c-b3b0-4608-a6b4-ffe46c113133.png)

**Comment by Galaxy-VN** [comment]
> 
[AuthMeUI-1.0.2.zip](https://github.com/Galaxy-VN/AuthMeUI/files/9337109/AuthMeUI-1.0.2.zip)

this should do

**Comment by tomzangsad** [comment]
It works.

**Comment by Galaxy-VN** [comment]
> It works.

ok i will post an update
